### ISSUE TITLE
Ability to maintain individual pool member state after conversion

### ISSUE THREAD

**Issue by arunhotra** [f5devcentral/f5-automation-config-converter#17]
### Is your feature request related to a problem? Please describe.
ACC currently does not track state of pool members. Also, after the conversion it lumps all pool members together and it is not possible to manage the state of individual pool members together.

As an example, this is how currently it converts the pool members.

![image](https://user-images.githubusercontent.com/4805118/109202370-e65f9b80-7770-11eb-8126-7a525f972c6c.png)

The downside of this is that you can only enable or disable all pool members at once. 

### Describe the solution you'd like

I propose that we convert it (if not by default, have an option or flag) as follows. In this case we can enable or disable individual pool members.

![image](https://user-images.githubusercontent.com/4805118/109233829-8da3f900-7798-11eb-8f54-b04c237d69ca.png)

We should also ensure that the pool members which are disabled prior to the conversion, should remain disabled after.

**Comment by mdditt2000** [comment]
@arunhotra closing this issue. ACC will only covert the input as shown above. ACC wont provide a expanded view. This can be done using GET request on the AS3 API using tools like postman or the F5 VScode extension.
