### ISSUE TITLE
Add Charon support for the most common BIG-IP objects

### ISSUE THREAD

**Issue by azahajkiewicz** [f5devcentral/f5-automation-config-converter#63]
### Is your feature request related to a problem? Please describe.
Problem: help brownfield customers migrating to AS3.
Customer UCS database was used to gather statistics of most common ACC unsupported objects.
Because it's not clear whether --unsupported means not supported by ACC or AS3, please take a look of those and, if possible, add a support for the most common ones.

### Describe the solution you'd like
Convert most common BIG-IP objects into AS3.

Count | Object type
------ | ---------------------------------
20547 | gtm wideip
29988 | gtm pool
11951 | security bot-defense signature
8490 | gtm pool srv
3581 | security shared-objects address-list
2167 | security bot-defense signature \
1232 | ltm snat
1172 | security shared-objects port-list
672 | net port-list
538 | gtm wideip srv
349 | asm policy
336 | security bot-defense signature-category \
287 | security protocol-inspection compliance-objects
286 | gtm wideip cname
279 | security bot-defense asm-profile
167 | security bot-defense profile
163 | ltm ifile
162 | gtm pool \
81 | auth tacacs

**Comment by mdditt2000** [comment]
Created Spike CHARON-570 to re-visit the “supported/unsupported” option in ACC. Required by Journeys

**Comment by mdditt2000** [comment]
This can be closed! Added to ACC 1.20
