### ISSUE TITLE
Error when -v option is used to filter output by virtual server name

### ISSUE THREAD

**Issue by janrenard** [f5devcentral/f5-automation-config-converter#77]
### Environment
 * ACC Version:1.1.17
 * AS3 Version: 3.33.0
 * BIG-IP Version: 14.1.4

### Summary
I'm trying to convert an existing F5 configuration into separate AS3 json files per virtual server. 
But I get an error when filtering the output by application (ACC option -v <virtual servername>). Trying the conversion on the full config file produces a proper json output. Tested on both 1.1.16 and 1.1.17 ACC versions.

### Steps To Reproduce
1. Convert following config:

#TMSH-VERSION: 14.1.4

apm client-packaging /PTNFRONTEND/client-packaging { }
apm resource sandbox /PTNFRONTEND/citrix-client-package {
    base-uri /PTNFRONTEND/public/citrix
    description "Sandbox for Citrix client package files"
}
apm resource sandbox /PTNFRONTEND/hosted-content {
    base-uri /PTNFRONTEND/public/share
    description "Sandbox for static contents"
}
}
ltm node /PTNFRONTEND/ND_hdp-dr-428 {
    address 192.168.206.159
    description "Aware prd"
}
ltm node /PTNFRONTEND/ND_hdp-dr-429 {
    address 192.168.206.160
    description "Aware prd"
}
ltm pool /PTNFRONTEND/RD600_POOL_aware-prd {
    members {
        /PTNFRONTEND/ND_hdp-dr-428:80 {
            address 192.168.206.159
        }
        /PTNFRONTEND/ND_hdp-dr-429:80 {
            address 192.168.206.160
        }
    }
    monitor /Common/tcp_half_open and /Common/http
}
ltm snatpool /PTNFRONTEND/SNAT_VLAN3338 {
    members {
        /PTNFRONTEND/91.227.209.24%600
    }
}
ltm virtual /PTNFRONTEND/RD600_VS_aware-prd_80 {
    destination /PTNFRONTEND/91.227.209.19%600:80
    ip-protocol tcp
    mask 255.255.255.255
    pool /PTNFRONTEND/RD600_POOL_aware-prd
    profiles {
        /Common/http { }
        /Common/tcp { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
ltm virtual-address /PTNFRONTEND/91.227.209.19%600 {
    address 91.227.209.19
    arp enabled
    mask 255.255.255.255
    traffic-group /Common/TG_PTNFRONTEND
    cookie-name .4a.partena-professional.be
    defaults-from /Common/cookie
}

2. Working command:
docker run --rm -v "$PWD":/app/data f5devcentral/f5-automation-config-converter:latest -c /app/data/bigip.conf -o /app/data/test.json

3. Failing command 
docker run --rm -v "$PWD":/app/data f5devcentral/f5-automation-config-converter:latest -c /app/data/bigip.conf -o /app/data/test.json -v /PTNFRONTEND/RD600_VS_aware-prd_80

4. Observe the following error message:
TypeError: Error filtering by application. Please open an issue at https://github.com/f5devcentral/f5-automation-config-converter/issues and include the following error:
Cannot read properties of undefined (reading 'Shared')
    at searchforObject (/app/src/postConverter/filterByApplication.js:40:28)
    at searchForObjectAndDependents (/app/src/postConverter/filterByApplication.js:53:20)
    at searchForDependents (/app/src/postConverter/filterByApplication.js:104:32)
    at module.exports (/app/src/postConverter/filterByApplication.js:144:9)
    at mainRunner (/app/src/main.js:72:27)
    at main (/app/src/main.js:117:30)

### Expected Behavior
An AS3 json file with the config for the specified virtual server

### Actual Behavior
No output is given except error output above

**Comment by mdditt2000** [comment]
Jira CHARON-567 for PM tracking

**Comment by p-semenov-f5** [comment]
Fixed in 1.18
