### ISSUE TITLE
Support for multiple virtual server or partitions filter

### ISSUE THREAD

**Issue by BarryHaines** [f5devcentral/f5-automation-config-converter#81]
### Is your feature request related to a problem? Please describe.
The virtual server filter for conversion only supports 1 virtual server and doesn't support filtering for a partition unless I only provide the .conf file with the specific configuration but this can be complicated in an automated process to get just this information, our automation steps include just downloading the UCS file.

### Describe the solution you'd like
Allow multiple instances of the -v or -form "vsName=" command and add a new filter that would allow the selection of a existing partition for conversion. 

### Describe alternatives you've considered
A way to possible extract just the BIG-IP configuration that needs to be converted by the ACC tool, this uses API calls to the BIG-IP to extract just specific objects for the conversion.

### Additional context
This solution would allow for the docker ACC tool to be integrated into an automation change and allow for scripting of the conversion.

**Comment by BarryHaines** [comment]
Hi Roman,

I have looked at f5-journey but it doesn't look like it has an REST-API, I only see a webgui for this tool and I haven't found any documentation that provides API usage details.

Regards,

Barry

**Comment by rjouhann** [comment]
Hello,

f5-journeys also have APIs, we should do a better job documenting those (will make sure we update the readme).

You can import the [openapi-schema.yaml](https://raw.githubusercontent.com/f5devcentral/f5-journeys/main/openapi-schema.yaml) into a [swagger](https://editor.swagger.io/).

<img width="1546" alt="Screen Shot 2022-02-18 at 8 33 33 AM" src="https://user-images.githubusercontent.com/25542366/154723871-f5a3034b-735e-461b-8d55-ab8722d65ee6.png">

Feel free to open an issue on [Journeys Github repo](https://github.com/f5devcentral/f5-journeys/issues) if you have any problem using those APIs.

Thanks & Regards,
Roman

**Comment by mdditt2000** [comment]
@BarryHaines do you have sometime to chat? I would like to show you another tool shown in the following demo https://youtu.be/sOBHv38xXNc

**Comment by BarryHaines** [comment]
@mdditt2000 thanks for the video, I will contact you directly to discuss further.

**Comment by mdditt2000** [comment]
Closing issue. Please reach out if you have any questions
