### ISSUE TITLE
Publish 1.19 to vscode extension marketplace

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/f5-automation-config-converter#84]
I can only see 1.18 in marketplace for vscode

https://marketplace.visualstudio.com/items?itemName=F5DevCentral.vscode-f5-chariot

**Comment by DumpySquare** [comment]
thanks.  this is on my list to get done

**Comment by DumpySquare** [comment]
vscode-f5-chariot v1.19.2 has been published to the marketplace:

[F5 ACC Chariot - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=F5DevCentral.vscode-f5-chariot)

**Comment by p-semenov-f5** [comment]
done
