### ISSUE TITLE
ACC does not include HTTPS (443) port in the prepared declaration

### ISSUE THREAD

**Issue by mnaumiuk** [f5devcentral/f5-automation-config-converter#87]
### Environment

 * ACC Version: latest (1.19.2)
 * AS3 Version: 3.33.0
 * BIG-IP Version: 14.1.4.4 & BIG-IP NEXT

### Summary

When a Virtual Server is configured with both:
- default HTTPS (443) port
- and HTTP profile
there is no virtualPort key in the output produced by ACC.

This declaration can be successfully deployed by AS3 on both BIG-IP and BIG-IP NEXT but it is not working on BIG-IP NEXT due to the lack of virtualPort option specified:
`RST cause: [27d50f7:2487] No local listener
`

Additional info:
- if the same service is configured without an HTTP profile and with port 443, the key "virtualPort" is present in the declaration produced by ACC
- if the same service is configured with an HTTP profile but with a different port (e.g. 444), the key "virtualPort" is also present in the declaration produced by ACC

### Steps To Reproduce

1. Convert the following config (IP:port is specified in config - 1.2.3.4:443):
```
ltm virtual /Common/vs_https {
    creation-time 2022-04-14:02:26:10
    destination /Common/1.2.3.4:443
    ip-protocol tcp
    last-modified-time 2022-04-14:02:40:51
    mask 255.255.255.255
    pool /Common/web_pool
    profiles {
        /Common/clientssl {
            context clientside
        }
        /Common/http { }
        /Common/tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
}
```

2. Declaration without "virtualPort" key is produced:

```
[root@centos8 master]# docker run --rm -v "$PWD":/app/data f5devcentral/f5-automation-config-converter:latest --ucs /app/data/as3_virtualport_http_profile.ucs --debug | grep vs_https -A20
            "vs_https": {
                "layer4": "tcp",
                "pool": "web_pool",
                "translateServerAddress": true,
                "translateServerPort": true,
                "class": "Service_HTTPS",
                "serverTLS": {
                    "bigip": "/Common/clientssl"
                },
                "profileHTTP": {
                    "bigip": "/Common/http"
                },
                "profileTCP": {
                    "bigip": "/Common/tcp"
                },
                "redirect80": false,
                "virtualAddresses": [
                    "1.2.3.4"
                ],
                "snat": "none"
            }
[root@centos8 master]#
```

3. However, If port 444 is configured instead of 443, "virtualPort" key is included in ACC output:

```
[root@centos8 master]# docker run --rm -v "$PWD":/app/data f5devcentral/f5-automation-config-converter:latest --ucs /app/data/as3_virtualport_http_profile_444.ucs --debug | grep vs_https -A21
            "vs_https": {
                "layer4": "tcp",
                "pool": "web_pool",
                "translateServerAddress": true,
                "translateServerPort": true,
                "class": "Service_HTTPS",
                "serverTLS": {
                    "bigip": "/Common/clientssl"
                },
                "profileHTTP": {
                    "bigip": "/Common/http"
                },
                "profileTCP": {
                    "bigip": "/Common/tcp"
                },
                "redirect80": false,
                "virtualAddresses": [
                    "1.2.3.4"
                ],
                "virtualPort": 444,
                "snat": "none"
            }
[root@centos8 master]#
```

4. Deploy AS3 declaration with vs_https service on BIG-IP NEXT and try to connect from the client (there is RST cause: [27d50f7:2487] No local listener)
NOTE: if we explicitly add virtualPort: 443 to the declaration, the vs_https on BIG-IP NEXT can be accessed.

### Expected Behavior
I think the expected behavior should be to copy a port of a service if it is present in the original config (even if it is the default one)

### Actual Behavior
If Virtual Server is configured with an HTTP profile &  default HTTPS (443) port - the virtualPort key is not included in AS3 declaration produced by ACC

**Comment by mnaumiuk** [comment]
AS3 schema for BIG-IP includes the defaults for virtualPort in Service_HTTPS class: [https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-https](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-https)

**Comment by sschadwick** [comment]
Unless specified otherwise, ACC will use the AS3 schema to remove default values from the results to reduce the amount of noise. This behavior can be overridden using the `--extended` flag.

**Comment by p-semenov-f5** [comment]
With --extended port is available in AS3 declaration

`{
    "class": "ADC",
    "schemaVersion": "3.36.0",
    "id": "urn:uuid:e06fc34a-231e-47f1-b779-245ebf46b0c2",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "vs_https": {
                "layer4": "tcp",
                "pool": "web_pool",
                "translateServerAddress": true,
                "translateServerPort": true,
                "class": "Service_HTTPS",
                "serverTLS": {
                    "bigip": "/Common/clientssl"
                },
                "profileHTTP": {
                    "bigip": "/Common/http"
                },
                "profileTCP": {
                    "bigip": "/Common/tcp"
                },
                "redirect80": false,
                "virtualAddresses": [
                    "1.2.3.4"
                ],
                "virtualPort": 443,
                "snat": "none"
            }
        }
    }
}`

I think it can be closed
