### ISSUE TITLE
TCP profile Ingress and Egress

### ISSUE THREAD

**Issue by BarryHaines** [f5devcentral/f5-automation-config-converter#89]
### Environment
 * ACC Version: Latest
 * AS3 Version: 3.35.0
 * BIG-IP Version: 16.1.0 and 14.1.4.6

### Summary
When converting a virtual server that has a separate clientside/serverside tcp profile the AS3 conversion only has the egress configuration and this fails to deploy to the BIG-IP because the ingress tcp profile is required but doesn't exist in the AS3 configuration.

### Steps To Reproduce
Just create virtual server with 2 separate TCP profiles for the clientside and serverside, then use ACC docker image to convert the configuration and notice that only the serverside profile is converted.

### Expected Behavior
Expecting to have the following output for the tcp profiles:

"profileTCP": {
                  "ingress": {
                     "bigip": "/Common/f5-tcp-wan"
                   },
                  "egress": {
                    "bigip": "/Common/tcp"
                  }
               },

### Actual Behavior
AS3 Output:
"vs_as3tcp-test-443": {
          "layer4": "tcp",
          "pool": "pl_as3mig_443",
          "translateServerAddress": true,
          "translateServerPort": true,
          "class": "Service_TCP",
          "profileTCP": { #Missing ingress profile
            "egress": {
              "bigip": "/Common/tcp"
            }
          },
          "virtualAddresses": [
            "10.1.0.51"
          ],
          "virtualPort": 443,
          "persistenceMethods": [],
          "snat": "auto"
        },

TMOS configuration output:
ltm virtual vs_as3tcp-test-443 {
    destination 10.1.0.51:https
    ip-protocol tcp
    mask 255.255.255.255
    pool pl_as3mig_443
    profiles {
        f5-tcp-wan { #This profile doesn't get converted
            context clientside
        }
        tcp {
            context serverside
        }
    }
    serverssl-use-sni disabled
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
    vs-index 32
}

**Comment by mdditt2000** [comment]
@BarryHaines looking to this issue. Here is my contact if you need to send me any additional information automation_toolchain_pm@f5.com

**Comment by mdditt2000** [comment]
@BarryHaines can you email me your qkview or bigip.conf. TMOS configuration above is break ACC using Docker/VScode. I file Jira CHARON-692

**Comment by mdditt2000** [comment]
@BarryHaines thanks for the configuration

I validated the configuration using your UCS file and i do see the correct TCP policy

```
"profileTCP": {
                    "ingress": {
                        "bigip": "/Common/f5-tcp-wan"
                    },
                    "egress": {
                        "bigip": "/Common/tcp"
                    }
                },
```
I will send you the converted file.

**Comment by mdditt2000** [comment]
Current version of ACC 1.21 works as expected. Closing issue. Thanks @BarryHaines please continue to open issue!
