### ISSUE TITLE
When using --next switch, schema version is not updated

### ISSUE THREAD

**Issue by azahajkiewicz** [f5devcentral/f5-automation-config-converter#92]
### Environment
 * ACC Version: 1.23

### Summary
1.22 introduced schema validation for BIG-IP Next. When using "--next=true",  schema version in the output should return schema used for Next generation, but it still returns schema as for classic.
,
### Steps To Reproduce
1. Convert following config with:
a) curl localhost:8080/converter -kX POST  --form "ucs=@<anyUCS>.ucs" --form "output=json-classic.json" --form "next=true" --form "verbose=true" |jq . > json-next.json

```
{
  "config": {
...
    "next": true,
...
  },
...
  "output": {
    "class": "ADC",
    "schemaVersion": "3.39.0",
    "id": "urn:uuid:0d741bed-21a8-4671-a04f-8358de1fb8c3",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
```

b) curl localhost:8080/converter -kX POST  --form "ucs=@<anyUCS>.ucs" --form "output=json-classic.json" --form "verbose=true" |jq . > json-classic.json

```
{
  "config": {
...
    "next": false,
...
  },
    "schemaVersion": "3.39.0",
    "id": "urn:uuid:2b563137-bf8c-4ad8-bba2-a29601d765ca",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
```

2. Observe the following:
```
  "logs": [
...
    "2022-09-04 16:31:29 INFO ------- AS3 Next ------",
    "2022-09-04 16:31:29 INFO 64 BIG-IP objects supported by ACC for AS3 Next",
    "2022-09-04 16:31:29 INFO 30 AS3 Next stanzas generated"
  ],
  "output": {
    "class": "ADC",
    "schemaVersion": "3.39.0",
    "id": "urn:uuid:0d741bed-21a8-4671-a04f-8358de1fb8c3",
    "label": "Converted Declaration",
    "remark": "Generated by Automation Config Converter",
```

**AS3 schema: 3.39.0**

### Expected Behavior
Latest AS3 info from VE BIG-IP Next:

```
{
    "version": "1.14.0",
    "release": "0",
    "schemaCurrent": "3.27.0",
    "schemaMinimum": "3.0.0"
}
```
schemaVersion returned from ACC with --next:true should match a version supported on BIG-IP Next.

### Actual Behavior
AS3 version on BIG-IP Next should be different than AS3 on a classic BIG-IP.

**Comment by mdditt2000** [comment]
Thanks @azahajkiewicz for opening this issue. Created Jira CHARON-745 and added to the next sprint

**Comment by p-semenov-f5** [comment]
I couldn't reproduce that from first glance:

ite_server2: ~/CHARON/source [develop] # node ./init -c ../IN/next/tt.conf -o ../OUT/next/test.json
2022-09-12 10:10:09 INFO 4 BIG-IP objects detected total
2022-09-12 10:10:09 INFO 4 BIG-IP objects recognized by AS3
2022-09-12 10:10:09 INFO 4 BIG-IP objects supported by ACC
2022-09-12 10:10:09 INFO 3 AS3 stanzas generated
ite_server2: ~/CHARON/source [develop] # cat ../OUT/next/test.json | grep "schemaVersion"
    "schemaVersion": "3.39.0",
ite_server2: ~/CHARON/source [develop] # node ./init -c ../IN/next/tt.conf -o ../OUT/next/test.json --next
2022-09-12 10:10:19 INFO AS3 Next conversion enabled
2022-09-12 10:10:20 INFO 4 BIG-IP objects detected total
2022-09-12 10:10:20 INFO 4 BIG-IP objects recognized by AS3
2022-09-12 10:10:20 INFO 4 BIG-IP objects supported by ACC
2022-09-12 10:10:20 INFO ------- AS3 Next ------
2022-09-12 10:10:20 INFO 4 BIG-IP objects supported by ACC for AS3 Next
2022-09-12 10:10:20 INFO 3 AS3 Next stanzas generated
ite_server2: ~/CHARON/source [develop] # cat ../OUT/next/test.json | grep "schemaVersion"
    "schemaVersion": "3.27.0",
ite_server2: ~/CHARON/source [develop] #

**Comment by p-semenov-f5** [comment]
And also we take version from here, there is no 3.39 inside:

  schemaVersion: {
    title: 'Schema version',
    description: 'Version of ADC Declaration schema this declaration uses',
    type: 'string',
    '$comment': 'IMPORTANT: In enum array, please put current schema version first, oldest-supported version last.  Keep enum array sorted most-recent-first.',
    enum: [
      '3.27.0', '3.26.0', '3.25.0',
      '3.24.0', '3.23.0', '3.22.0',
      '3.21.0', '3.20.0', '3.19.0',
      '3.18.0', '3.17.0', '3.16.0',
      '3.15.0', '3.14.0', '3.13.0',
      '3.12.0', '3.11.0', '3.10.0',
      '3.9.0',  '3.8.1',  '3.7.1',
      '3.6.0',  '3.5.2',  '3.5.1',
      '3.4.0',  '3.3.0',  '3.2.0',
      '3.1.0',  '3.0.0'
    ]
  }

**Comment by p-semenov-f5** [comment]
No repro through the server requests:

ite_server2: ~/CHARON/source [develop] # curl localhost:8080/converter -X POST --form "conf=@../IN/next/tt.conf" --form "output=tt_http2.json" |jq . | grep "schemaVersion"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3078  100   900  100  2178  13153  31832 --:--:-- --:--:-- --:--:-- 32029
  **"schemaVersion": "3.39.0",**
ite_server2: ~/CHARON/source [develop] # curl localhost:8080/converter -X POST --form "conf=@../IN/next/tt.conf" --form "output=tt_http2.json" --form "next=true" |jq . | grep "schemaVersion"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2886  100   611  100  2275    685   2554 --:--:-- --:--:-- --:--:--  2553
  **"schemaVersion": "3.27.0",**
ite_server2: ~/CHARON/source [develop] #

**Comment by p-semenov-f5** [comment]
Right now I can see that problem again in develop:

ite_server2: ~/CHARON/source [develop] # node ./init -c ../IN/next/tt_tcp.conf -o ../OUT/next/test.json --next
2022-09-26 14:16:39 INFO AS3 Next conversion enabled
{
  title: 'Schema version',
  description: 'Version of ADC Declaration schema this declaration uses',
  type: 'string',
  '$comment': 'IMPORTANT: In enum array, please put current schema version first, oldest-supported version last.  Keep enum array sorted most-recent-first.',
  enum: [
    '3.39.0', '3.38.0', '3.37.0', '3.36.0',
    '3.35.0', '3.34.0', '3.33.0', '3.32.0',
    '3.31.0', '3.30.0', '3.29.0', '3.28.0',
    '3.27.0', '3.26.0', '3.25.0', '3.24.0',
    '3.23.0', '3.22.0', '3.21.0', '3.20.0',
    '3.19.0', '3.18.0', '3.17.0', '3.16.0',
    '3.15.0', '3.14.0', '3.13.0', '3.12.0',
    '3.11.0', '3.10.0', '3.9.0',  '3.8.1',
    '3.7.1',  '3.6.0',  '3.5.2',  '3.5.1',
    '3.4.0',  '3.3.0',  '3.2.0',  '3.1.0',
    '3.0.0'
  ]
}
3.39.0
2022-09-26 14:16:40 INFO 3 BIG-IP objects detected total
2022-09-26 14:16:40 INFO 3 BIG-IP objects recognized by AS3
2022-09-26 14:16:40 INFO 3 BIG-IP objects supported by ACC
2022-09-26 14:16:40 INFO ------- AS3 Next ------
2022-09-26 14:16:40 INFO 3 BIG-IP objects supported by ACC for AS3 Next
2022-09-26 14:16:40 INFO 2 AS3 Next stanzas generated
ite_server2: ~/CHARON/source [develop] #
